include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    public_member_api_docs: true
    always_specify_types: true
    prefer_final_locals: true
    prefer_const_constructors: true
    unnecessary_this: true
    avoid_print: true
    directives_ordering: true
    sort_pub_dependencies: true
    sort_constructors_first: true
