// Mocks generated by Mockito 5.4.6 from annotations
// in chenron/test/features/settings/controller/config_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i9;

import 'package:chenron/features/settings/service/config_service.dart' as _i3;
import 'package:chenron/features/settings/service/data_settings_service.dart'
    as _i7;
import 'package:chenron/features/theme/state/theme_controller.dart' as _i10;
import 'package:database/database.dart' as _i5;
import 'package:database/main.dart' as _i6;
import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:signals/signals_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignal_0<T> extends _i1.SmartFake implements _i2.Signal<T> {
  _FakeSignal_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i3.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.UserConfigResult?> getUserConfig() => (super.noSuchMethod(
        Invocation.method(
          #getUserConfig,
          [],
        ),
        returnValue: _i4.Future<_i5.UserConfigResult?>.value(),
      ) as _i4.Future<_i5.UserConfigResult?>);

  @override
  _i4.Future<List<_i5.UserThemeResult>> getAllUserThemes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUserThemes,
          [],
        ),
        returnValue: _i4.Future<List<_i5.UserThemeResult>>.value(
            <_i5.UserThemeResult>[]),
      ) as _i4.Future<List<_i5.UserThemeResult>>);

  @override
  _i4.Future<_i6.BackupSetting?> getBackupSettings() => (super.noSuchMethod(
        Invocation.method(
          #getBackupSettings,
          [],
        ),
        returnValue: _i4.Future<_i6.BackupSetting?>.value(),
      ) as _i4.Future<_i6.BackupSetting?>);

  @override
  _i4.Future<void> updateBackupSettings({
    required String? id,
    String? backupInterval,
    String? backupPath,
    bool? clearInterval = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupSettings,
          [],
          {
            #id: id,
            #backupInterval: backupInterval,
            #backupPath: backupPath,
            #clearInterval: clearInterval,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserConfig({
    required String? configId,
    required bool? defaultArchiveIs,
    required bool? defaultArchiveOrg,
    required String? archiveOrgS3AccessKey,
    required String? archiveOrgS3SecretKey,
    required String? selectedThemeKey,
    required _i6.ThemeType? selectedThemeType,
    required int? timeDisplayFormat,
    required int? itemClickAction,
    String? cacheDirectory,
    required bool? showDescription,
    required bool? showImages,
    required bool? showTags,
    required bool? showCopyLink,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserConfig,
          [],
          {
            #configId: configId,
            #defaultArchiveIs: defaultArchiveIs,
            #defaultArchiveOrg: defaultArchiveOrg,
            #archiveOrgS3AccessKey: archiveOrgS3AccessKey,
            #archiveOrgS3SecretKey: archiveOrgS3SecretKey,
            #selectedThemeKey: selectedThemeKey,
            #selectedThemeType: selectedThemeType,
            #timeDisplayFormat: timeDisplayFormat,
            #itemClickAction: itemClickAction,
            #cacheDirectory: cacheDirectory,
            #showDescription: showDescription,
            #showImages: showImages,
            #showTags: showTags,
            #showCopyLink: showCopyLink,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DataSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSettingsService extends _i1.Mock
    implements _i7.DataSettingsService {
  MockDataSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> getDefaultDatabasePath() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultDatabasePath,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getDefaultDatabasePath,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String?> getCustomDatabasePath() => (super.noSuchMethod(
        Invocation.method(
          #getCustomDatabasePath,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> setCustomDatabasePath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #setCustomDatabasePath,
          [path],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.File?> exportDatabase(_i9.Directory? destination) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportDatabase,
          [destination],
        ),
        returnValue: _i4.Future<_i9.File?>.value(),
      ) as _i4.Future<_i9.File?>);

  @override
  _i4.Future<_i9.File?> importDatabase(_i9.File? sourceFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #importDatabase,
          [sourceFile],
        ),
        returnValue: _i4.Future<_i9.File?>.value(),
      ) as _i4.Future<_i9.File?>);
}

/// A class which mocks [ThemeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeController extends _i1.Mock implements _i10.ThemeController {
  MockThemeController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Signal<({_i11.ThemeData dark, _i11.ThemeData light})>
      get currentThemeSignal => (super.noSuchMethod(
            Invocation.getter(#currentThemeSignal),
            returnValue:
                _FakeSignal_0<({_i11.ThemeData dark, _i11.ThemeData light})>(
              this,
              Invocation.getter(#currentThemeSignal),
            ),
          ) as _i2.Signal<({_i11.ThemeData dark, _i11.ThemeData light})>);

  @override
  void seedCachedTheme(({_i11.ThemeData dark, _i11.ThemeData light})? theme) =>
      super.noSuchMethod(
        Invocation.method(
          #seedCachedTheme,
          [theme],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> changeTheme(
    String? themeKey,
    _i6.ThemeType? themeType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeTheme,
          [
            themeKey,
            themeType,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setCurrentTheme() => (super.noSuchMethod(
        Invocation.method(
          #setCurrentTheme,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
