include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - avoid_dynamic_calls
    - cancel_subscriptions
    - close_sinks
    - prefer_final_locals
    - prefer_const_constructors
