// Mocks generated by Mockito 5.4.6 from annotations
// in chenron/test/features/settings/state/archive_settings_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chenron/features/settings/service/config_service.dart' as _i2;
import 'package:database/database.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i2.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserConfigResult?> getUserConfig() => (super.noSuchMethod(
        Invocation.method(
          #getUserConfig,
          [],
        ),
        returnValue: _i3.Future<_i4.UserConfigResult?>.value(),
      ) as _i3.Future<_i4.UserConfigResult?>);

  @override
  _i3.Future<List<_i4.UserThemeResult>> getAllUserThemes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUserThemes,
          [],
        ),
        returnValue: _i3.Future<List<_i4.UserThemeResult>>.value(
            <_i4.UserThemeResult>[]),
      ) as _i3.Future<List<_i4.UserThemeResult>>);

  @override
  _i3.Future<_i4.BackupSetting?> getBackupSettings() => (super.noSuchMethod(
        Invocation.method(
          #getBackupSettings,
          [],
        ),
        returnValue: _i3.Future<_i4.BackupSetting?>.value(),
      ) as _i3.Future<_i4.BackupSetting?>);

  @override
  _i3.Future<void> updateBackupSettings({
    required String? id,
    String? backupInterval,
    String? backupPath,
    bool? clearInterval = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupSettings,
          [],
          {
            #id: id,
            #backupInterval: backupInterval,
            #backupPath: backupPath,
            #clearInterval: clearInterval,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserConfig({
    required String? configId,
    required bool? defaultArchiveIs,
    required bool? defaultArchiveOrg,
    required String? archiveOrgS3AccessKey,
    required String? archiveOrgS3SecretKey,
    required String? selectedThemeKey,
    required _i4.ThemeType? selectedThemeType,
    required int? timeDisplayFormat,
    required int? itemClickAction,
    String? cacheDirectory,
    required bool? showDescription,
    required bool? showImages,
    required bool? showTags,
    required bool? showCopyLink,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserConfig,
          [],
          {
            #configId: configId,
            #defaultArchiveIs: defaultArchiveIs,
            #defaultArchiveOrg: defaultArchiveOrg,
            #archiveOrgS3AccessKey: archiveOrgS3AccessKey,
            #archiveOrgS3SecretKey: archiveOrgS3SecretKey,
            #selectedThemeKey: selectedThemeKey,
            #selectedThemeType: selectedThemeType,
            #timeDisplayFormat: timeDisplayFormat,
            #itemClickAction: itemClickAction,
            #cacheDirectory: cacheDirectory,
            #showDescription: showDescription,
            #showImages: showImages,
            #showTags: showTags,
            #showCopyLink: showCopyLink,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateArchiveSection({
    required String? configId,
    required bool? defaultArchiveIs,
    required bool? defaultArchiveOrg,
    required String? archiveOrgS3AccessKey,
    required String? archiveOrgS3SecretKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArchiveSection,
          [],
          {
            #configId: configId,
            #defaultArchiveIs: defaultArchiveIs,
            #defaultArchiveOrg: defaultArchiveOrg,
            #archiveOrgS3AccessKey: archiveOrgS3AccessKey,
            #archiveOrgS3SecretKey: archiveOrgS3SecretKey,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDisplaySection({
    required String? configId,
    required int? timeDisplayFormat,
    required int? itemClickAction,
    required String? cacheDirectory,
    required bool? showDescription,
    required bool? showImages,
    required bool? showTags,
    required bool? showCopyLink,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplaySection,
          [],
          {
            #configId: configId,
            #timeDisplayFormat: timeDisplayFormat,
            #itemClickAction: itemClickAction,
            #cacheDirectory: cacheDirectory,
            #showDescription: showDescription,
            #showImages: showImages,
            #showTags: showTags,
            #showCopyLink: showCopyLink,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateThemeSection({
    required String? configId,
    required String? selectedThemeKey,
    required _i4.ThemeType? selectedThemeType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateThemeSection,
          [],
          {
            #configId: configId,
            #selectedThemeKey: selectedThemeKey,
            #selectedThemeType: selectedThemeType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
