// Mocks generated by Mockito 5.4.6 from annotations
// in chenron/test/features/settings/state/database_settings_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i2;

import 'package:chenron/features/settings/service/data_settings_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DataSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSettingsService extends _i1.Mock
    implements _i3.DataSettingsService {
  MockDataSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> getDefaultDatabasePath() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultDatabasePath,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getDefaultDatabasePath,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String?> getCustomDatabasePath() => (super.noSuchMethod(
        Invocation.method(
          #getCustomDatabasePath,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> setCustomDatabasePath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #setCustomDatabasePath,
          [path],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.File> exportDatabase(_i2.Directory? destination) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportDatabase,
          [destination],
        ),
        returnValue: _i4.Future<_i2.File>.value(_FakeFile_0(
          this,
          Invocation.method(
            #exportDatabase,
            [destination],
          ),
        )),
      ) as _i4.Future<_i2.File>);

  @override
  _i4.Future<_i2.File> importDatabase(_i2.File? sourceFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #importDatabase,
          [sourceFile],
        ),
        returnValue: _i4.Future<_i2.File>.value(_FakeFile_0(
          this,
          Invocation.method(
            #importDatabase,
            [sourceFile],
          ),
        )),
      ) as _i4.Future<_i2.File>);
}
