// Mocks generated by Mockito 5.4.6 from annotations
// in chenron/test/features/settings/state/theme_settings_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chenron/features/theme/state/theme_notifier.dart' as _i3;
import 'package:database/database.dart' as _i6;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:signals/signals_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignal_0<T> extends _i1.SmartFake implements _i2.Signal<T> {
  _FakeSignal_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ThemeNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeNotifier extends _i1.Mock implements _i3.ThemeNotifier {
  MockThemeNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Signal<({_i4.ThemeData dark, _i4.ThemeData light})>
      get currentThemeSignal => (super.noSuchMethod(
            Invocation.getter(#currentThemeSignal),
            returnValue:
                _FakeSignal_0<({_i4.ThemeData dark, _i4.ThemeData light})>(
              this,
              Invocation.getter(#currentThemeSignal),
            ),
          ) as _i2.Signal<({_i4.ThemeData dark, _i4.ThemeData light})>);

  @override
  void seedCachedTheme(({_i4.ThemeData dark, _i4.ThemeData light})? theme) =>
      super.noSuchMethod(
        Invocation.method(
          #seedCachedTheme,
          [theme],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> changeTheme(
    String? themeKey,
    _i6.ThemeType? themeType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeTheme,
          [
            themeKey,
            themeType,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCurrentTheme() => (super.noSuchMethod(
        Invocation.method(
          #setCurrentTheme,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
