// Mocks generated by Mockito 5.4.6 from annotations
// in chenron/test/features/viewer/viewer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chenron/database/database.dart' as _i4;
import 'package:chenron/features/settings/controller/config_controller.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:signals/signals_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlutterSignal_0<T> extends _i1.SmartFake
    implements _i2.FlutterSignal<T> {
  _FakeFlutterSignal_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigController].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigController extends _i1.Mock implements _i3.ConfigController {
  MockConfigController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterSignal<bool> get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: _FakeFlutterSignal_0<bool>(
          this,
          Invocation.getter(#isLoading),
        ),
      ) as _i2.FlutterSignal<bool>);

  @override
  _i2.FlutterSignal<String?> get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _FakeFlutterSignal_0<String?>(
          this,
          Invocation.getter(#error),
        ),
      ) as _i2.FlutterSignal<String?>);

  @override
  _i2.FlutterSignal<_i4.UserConfig?> get userConfig => (super.noSuchMethod(
        Invocation.getter(#userConfig),
        returnValue: _FakeFlutterSignal_0<_i4.UserConfig?>(
          this,
          Invocation.getter(#userConfig),
        ),
      ) as _i2.FlutterSignal<_i4.UserConfig?>);

  @override
  _i2.FlutterSignal<_i3.ThemeChoice?> get selectedThemeChoice =>
      (super.noSuchMethod(
        Invocation.getter(#selectedThemeChoice),
        returnValue: _FakeFlutterSignal_0<_i3.ThemeChoice?>(
          this,
          Invocation.getter(#selectedThemeChoice),
        ),
      ) as _i2.FlutterSignal<_i3.ThemeChoice?>);

  @override
  _i2.FlutterSignal<List<_i3.ThemeChoice>> get availableThemes =>
      (super.noSuchMethod(
        Invocation.getter(#availableThemes),
        returnValue: _FakeFlutterSignal_0<List<_i3.ThemeChoice>>(
          this,
          Invocation.getter(#availableThemes),
        ),
      ) as _i2.FlutterSignal<List<_i3.ThemeChoice>>);

  @override
  _i2.FlutterSignal<bool> get defaultArchiveIs => (super.noSuchMethod(
        Invocation.getter(#defaultArchiveIs),
        returnValue: _FakeFlutterSignal_0<bool>(
          this,
          Invocation.getter(#defaultArchiveIs),
        ),
      ) as _i2.FlutterSignal<bool>);

  @override
  _i2.FlutterSignal<bool> get defaultArchiveOrg => (super.noSuchMethod(
        Invocation.getter(#defaultArchiveOrg),
        returnValue: _FakeFlutterSignal_0<bool>(
          this,
          Invocation.getter(#defaultArchiveOrg),
        ),
      ) as _i2.FlutterSignal<bool>);

  @override
  _i2.FlutterSignal<String?> get archiveOrgS3AccessKey => (super.noSuchMethod(
        Invocation.getter(#archiveOrgS3AccessKey),
        returnValue: _FakeFlutterSignal_0<String?>(
          this,
          Invocation.getter(#archiveOrgS3AccessKey),
        ),
      ) as _i2.FlutterSignal<String?>);

  @override
  _i2.FlutterSignal<String?> get archiveOrgS3SecretKey => (super.noSuchMethod(
        Invocation.getter(#archiveOrgS3SecretKey),
        returnValue: _FakeFlutterSignal_0<String?>(
          this,
          Invocation.getter(#archiveOrgS3SecretKey),
        ),
      ) as _i2.FlutterSignal<String?>);

  @override
  _i2.FlutterSignal<int> get timeDisplayFormat => (super.noSuchMethod(
        Invocation.getter(#timeDisplayFormat),
        returnValue: _FakeFlutterSignal_0<int>(
          this,
          Invocation.getter(#timeDisplayFormat),
        ),
      ) as _i2.FlutterSignal<int>);

  @override
  _i2.FlutterSignal<int> get itemClickAction => (super.noSuchMethod(
        Invocation.getter(#itemClickAction),
        returnValue: _FakeFlutterSignal_0<int>(
          this,
          Invocation.getter(#itemClickAction),
        ),
      ) as _i2.FlutterSignal<int>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateSelectedTheme(_i3.ThemeChoice? choice) => super.noSuchMethod(
        Invocation.method(
          #updateSelectedTheme,
          [choice],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDefaultArchiveIs({required bool? enabled}) => super.noSuchMethod(
        Invocation.method(
          #updateDefaultArchiveIs,
          [],
          {#enabled: enabled},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDefaultArchiveOrg({required bool? enabled}) => super.noSuchMethod(
        Invocation.method(
          #updateDefaultArchiveOrg,
          [],
          {#enabled: enabled},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateArchiveOrgS3AccessKey(String? value) => super.noSuchMethod(
        Invocation.method(
          #updateArchiveOrgS3AccessKey,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateArchiveOrgS3SecretKey(String? value) => super.noSuchMethod(
        Invocation.method(
          #updateArchiveOrgS3SecretKey,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateTimeDisplayFormat(int? value) => super.noSuchMethod(
        Invocation.method(
          #updateTimeDisplayFormat,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateItemClickAction(int? value) => super.noSuchMethod(
        Invocation.method(
          #updateItemClickAction,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> saveSettings() => (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  bool hasUnsavedChanges() => (super.noSuchMethod(
        Invocation.method(
          #hasUnsavedChanges,
          [],
        ),
        returnValue: false,
      ) as bool);
}
