// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';
import 'package:drift/internal/migrations.dart';
import 'schema_v12.dart' as v12;
import 'schema_v14.dart' as v14;
import 'schema_v15.dart' as v15;
import 'schema_v16.dart' as v16;

class GeneratedHelper implements SchemaInstantiationHelper {
  @override
  GeneratedDatabase databaseForVersion(QueryExecutor db, int version) {
    switch (version) {
      case 12:
        return v12.DatabaseAtV12(db);
      case 14:
        return v14.DatabaseAtV14(db);
      case 15:
        return v15.DatabaseAtV15(db);
      case 16:
        return v16.DatabaseAtV16(db);
      default:
        throw MissingSchemaException(version, versions);
    }
  }

  static const versions = const [12, 14, 15, 16];
}
